[project]
name = "relaxed-algos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cvxpy>=1.7.3",
    "networkx>=3.5",
    "plotly>=6.4.0",
]
